-- fincoach schema (H2, MODE=Oracle) — generated to match the columns referenced in mappers/*.xml
-- All statements are idempotent (IF NOT EXISTS) so spring.sql.init.mode=always is safe to re-run on every startup.

CREATE SEQUENCE IF NOT EXISTS SEQ_USERS_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_MYTRANS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_FNO START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID     INT PRIMARY KEY,
    LOGIN_ID    VARCHAR(100) NOT NULL UNIQUE,
    USER_NAME   VARCHAR(100),
    NICKNAME    VARCHAR(100) UNIQUE,
    EMAIL       VARCHAR(200) UNIQUE,
    PASSWORD    VARCHAR(200),
    STATUS      VARCHAR(1) DEFAULT 'Y',
    LAST_LOGIN  DATE,
    CREATED_AT  DATE DEFAULT CURRENT_DATE,
    B_AMOUNT    INT,
    RESET_DATE  INT,
    LOGIN_COUNT INT DEFAULT 0,
    LOCK_UNTIL  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUTH_ACCOUNT (
    USER_ID          INT PRIMARY KEY REFERENCES USERS(USER_ID),
    LOGIN_TYPE       VARCHAR(20),
    PROVIDER_USER_ID VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS FIXEDTRANS (
    FIXED_ID   INT PRIMARY KEY,
    NAME       VARCHAR(200),
    TRANS_DATE DATE,
    AMOUNT     INT,
    CATEGORY   VARCHAR(50),
    PAY_DAY    INT,
    USER_ID    INT REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS MYTRANS (
    TRAN_ID         INT PRIMARY KEY,
    TITLE           VARCHAR(200),
    TRANS_DATE      DATE,
    ORIGINAL_AMOUNT INT,
    IS_SHARED       VARCHAR(1) DEFAULT 'N',
    CATEGORY        VARCHAR(50),
    TYPE            VARCHAR(3),
    MEMO            VARCHAR(500),
    USER_ID         INT REFERENCES USERS(USER_ID),
    GROUPB_ID       INT,
    FIXED_ID        INT
);

CREATE SEQUENCE IF NOT EXISTS SEQ_COACHING START WITH 1 INCREMENT BY 1;

-- AI coaching: nudges (ROLE='NUDGE') and the chat thread that follows one (ROLE='USER'/'COACH').
-- THREAD_ID on a NUDGE row equals its own MESSAGE_ID; replies reference that same THREAD_ID.
CREATE TABLE IF NOT EXISTS COACHING_MESSAGE (
    MESSAGE_ID      INT PRIMARY KEY,
    USER_ID         INT REFERENCES USERS(USER_ID),
    THREAD_ID       INT NOT NULL,
    ROLE            VARCHAR(10) NOT NULL,
    CONTENT         VARCHAR(2000),
    CATEGORY        VARCHAR(50),
    ORIGINAL_AMOUNT INT,
    AVG_AMOUNT      INT,
    ACCEPTED        VARCHAR(1),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS SEQ_TREND START WITH 1 INCREMENT BY 1;

-- AI coaching: monthly macro spending-trend analysis, cached per (user, year-month)
-- so Gemini is called at most once per user per month regardless of how many times
-- the growth report is opened that month.
CREATE TABLE IF NOT EXISTS SPENDING_TREND (
    TREND_ID    INT PRIMARY KEY,
    USER_ID     INT REFERENCES USERS(USER_ID),
    YEAR_MONTH  VARCHAR(7) NOT NULL,
    CONTENT     VARCHAR(2000),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (USER_ID, YEAR_MONTH)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_CHALLENGE START WITH 1 INCREMENT BY 1;

-- AI 코칭 채팅에서 사용자가 동의한 구체적 실행 목표(챌린지). 진행률/성공 여부는 저장하지 않고
-- 매번 실제 거래 데이터(MYTRANS)로 프론트에서 실시간 계산한다 — 배치/크론이 필요 없다.
CREATE TABLE IF NOT EXISTS CHALLENGE (
    CHALLENGE_ID  INT PRIMARY KEY,
    USER_ID       INT REFERENCES USERS(USER_ID),
    THREAD_ID     INT,
    CATEGORY      VARCHAR(50),
    TITLE         VARCHAR(200),
    METRIC_TYPE   VARCHAR(10) NOT NULL,
    TARGET_VALUE  INT NOT NULL,
    START_DATE    DATE NOT NULL,
    END_DATE      DATE NOT NULL,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
